### ISSUE TITLE
全屏抽屉Android机卡顿

### ISSUE THREAD

**Issue by VolnaTime** [XiaokangLei/ColorUI-GA#10]
您好，在使用ColorUI GA组件库的时候发现一个问题，全屏抽屉卡顿很明显。
手机型号：小米10
问题：打开全屏抽屉有明显卡顿

**Comment by XiaokangLei** [comment]
已解决，请使用最新代码查看效果。

**Comment by VolnaTime** [comment]
> 已解决，请使用最新代码查看效果。

感谢~
