### ISSUE TITLE
文档地址打开没内容

### ISSUE THREAD

**Issue by SillyNiu** [XiaokangLei/ColorUI-GA#20]
文档地址打开没内容
![image](https://github.com/XiaokangLei/ColorUI-GA/assets/35002463/4ddc8128-772f-4f5e-80e1-82d4199d68fd)

**Comment by XiaokangLei** [comment]
> 文档地址打开没内容 ![image](https://private-user-images.githubusercontent.com/35002463/264200122-4ddc8128-772f-4f5e-80e1-82d4199d68fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDI5NDUsIm5iZiI6MTcwMzYwMjY0NSwicGF0aCI6Ii8zNTAwMjQ2My8yNjQyMDAxMjItNGRkYzgxMjgtNzcyZi00ZjVlLTgwZTEtODJkNDE5OWQ2OGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE0NTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzOTViYmYwNjM3M2FjMzdmODg0NDI1MWVhOWUyNWVmNWU0MGU3NTkzZjA5YzExNzgyMmRhMjAwYjU0MTcyMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m4uHEpiY8kdEoQkhC14f8fBwo-6hP1A9r8LoN6-186k)

域名不续费了，用这个
https://xiaokanglei.github.io/ColorUI-GA-Docs/
https://xiaokanglei.github.io/ColorUI-GA-Docs/h5/northlandshop/demo.html

**Comment by XiaokangLei** [comment]
> 文档地址打开没内容 ![image](https://private-user-images.githubusercontent.com/35002463/264200122-4ddc8128-772f-4f5e-80e1-82d4199d68fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDI5OTAsIm5iZiI6MTcwMzYwMjY5MCwicGF0aCI6Ii8zNTAwMjQ2My8yNjQyMDAxMjItNGRkYzgxMjgtNzcyZi00ZjVlLTgwZTEtODJkNDE5OWQ2OGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE0NTgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OGFiYzUxNzM3NjQ5OWYyOThjY2NlZmYzMjBiYjU1ZTIzNzY0MjNkMTlmYjAyMTFhMDQ5YmEwZGMyZjIyZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f9WpGdXFZA-a6z0YT5lGzbulbmKvb0Bk_Zmf1rHvh0k)

尽量科学上网，网站挂在GitHub上的
之前域名不续费了，用这个
https://xiaokanglei.github.io/ColorUI-GA-Docs/
https://xiaokanglei.github.io/ColorUI-GA-Docs/h5/northlandshop/demo.html
