### ISSUE TITLE
one.x-artspace.cn下的内容都挂了

### ISSUE THREAD

**Issue by cheakin** [XiaokangLei/ColorUI-GA#23]
http://[one.x-artspace.cn](http://one.x-artspace.cn/ColorUI-GA-Docs/)/ColorUI-GA-Docs/ 文档挂了
https://[one.x-artspace.cn](https://one.x-artspace.cn/ColorUI-GA-Docs/h5/northlandshop/demo.html)/ColorUI-GA-Docs/h5/northlandshop/demo.html 小程序示例也挂了

**Comment by XiaokangLei** [comment]
域名不续费了，用这个
https://xiaokanglei.github.io/ColorUI-GA-Docs/
https://xiaokanglei.github.io/ColorUI-GA-Docs/h5/northlandshop/demo.html

**Comment by XiaokangLei** [comment]
> http://[one.x-artspace.cn](http://one.x-artspace.cn/ColorUI-GA-Docs/)/ColorUI-GA-Docs/ 文档挂了 https://[one.x-artspace.cn](https://one.x-artspace.cn/ColorUI-GA-Docs/h5/northlandshop/demo.html)/ColorUI-GA-Docs/h5/northlandshop/demo.html 小程序示例也挂了

域名不续费了，用这个
https://xiaokanglei.github.io/ColorUI-GA-Docs/
https://xiaokanglei.github.io/ColorUI-GA-Docs/h5/northlandshop/demo.html
