### ISSUE TITLE
关于全局引入wxss样式后，局部组件无法生效的问题

### ISSUE THREAD

**Issue by kongxiyi** [XiaokangLei/ColorUI-GA#5]
你好，非常感谢这个很好用的工具，先给一个star~目前有一个疑惑，就是我全局引入wxss样式，也就是我在app.wxss中引入以下代码
```
@import "colorui/main.wxss";
@import "colorui/icon.wxss";
```
首先，在page页面是生效的，但是如果我page页面注册引入一个component，component本身的wxss如果未引入以上代码，会造成component样式失效的问题，请问有解决的办法吗？

**Comment by XiaokangLei** [comment]
可以在app.json中引入全局component，在usingComponents内添加。
引用component的Page的xxx.json就不用写局部引入了
