### ISSUE TITLE
[ app.json 文件内容错误] app.json: ["usingComponents"]["cu-custom"]: "./colorui/components/cu-custom" 未找到(env: Windows,mp,1.06.2210310; lib: 2.19.4)

### ISSUE THREAD

**Issue by a328093070** [XiaokangLei/ColorUI-GA#7]
我是一个新手
在按照文档引入组件后报这个错，请问怎么解决
[ app.json 文件内容错误] app.json: ["usingComponents"]["cu-custom"]: "./colorui/components/cu-custom" 未找到(env: Windows,mp,1.06.2210310; lib: 2.19.4)

**Comment by XiaokangLei** [comment]
> 我是一个新手 在按照文档引入组件后报这个错，请问怎么解决 [ app.json 文件内容错误] app.json: ["usingComponents"]["cu-custom"]: "./colorui/components/cu-custom" 未找到(env: Windows,mp,1.06.2210310; lib: 2.19.4)

抱歉，文档写法有误，已更正，最后少写了一个cu-custom，应该是"/colorui/components/cu-custom/cu-custom"
