### ISSUE TITLE
自定义顶部导航栏返回bug

### ISSUE THREAD

**Issue by echome123** [XiaokangLei/ColorUI-GA#8]
目前从小程序一级页面，跳转到二级页面，使用顶部导航的返回按钮正常没问题。

不出意外的话，就会出现意外：
当用户通过二级页面二维码直接进入的话，这个返回按钮就失灵了，他找不到上一级返回页面，就没反应了。

不知道能否做一个判断处理，假如存在上一级页面就正常返回，不存在上一级页面的返回按钮，变成返回首页，或者怎么能自定义跳转路径的办法解决这个问题。

因为官方原生顶部导航遇到没有上一级页面，就会自动变成一个首页的图标来跳转。

**Comment by XiaokangLei** [comment]
> 目前从小程序一级页面，跳转到二级页面，使用顶部导航的返回按钮正常没问题。
> 
> 不出意外的话，就会出现意外： 当用户通过二级页面二维码直接进入的话，这个返回按钮就失灵了，他找不到上一级返回页面，就没反应了。
> 
> 不知道能否做一个判断处理，假如存在上一级页面就正常返回，不存在上一级页面的返回按钮，变成返回首页，或者怎么能自定义跳转路径的办法解决这个问题。
> 
> 因为官方原生顶部导航遇到没有上一级页面，就会自动变成一个首页的图标来跳转。

感谢提出BUG，该问题已解决。解决思路：在cu-customs组件中，通过getCurrentPages()接口，获取当前页面的长度.length，当length为1时，当前场景为点开分享或从其他页面第一次进入，并且isBack="{{true}}"此时设置主页面图标并链接主页面。
具体代码可下载源码进行查看。

**Comment by echome123** [comment]
您这个修复效率真高效，哈哈，感谢！

**Comment by echome123** [comment]
不过您修复之后的这个，我尝试之后，想再提个小建议：
1、首页图标跳转地址做成可自定义的，因为有些程序可能首页地址不是/pages/index/index。 可以像isBack="{{true}}" 这个方式一样，在wxml文件标签上面直接覆盖，类似 indexpath = "/home/index/index"

2、当导航配置了backText内容之后，这个backText会跟随返回图标和首页图标一同出现，这时有一个差别就是，返回上一页的时候，图标和文字点击都会跳转（看代码是包在同一个view里面了），但是新修复的返回首页图标和backText同时在一起显示，此时的backText点击是没反应的，测试时候因为感官上的意识，一直再点击backText文字，没有反应，再去点击图标才有效果。

**Comment by XiaokangLei** [comment]
> 不过您修复之后的这个，我尝试之后，想再提个小建议： 1、首页图标跳转地址做成可自定义的，因为有些程序可能首页地址不是/pages/index/index。 可以像isBack="{{true}}" 这个方式一样，在wxml文件标签上面直接覆盖，类似 indexpath = "/home/index/index"
> 
> 2、当导航配置了backText内容之后，这个backText会跟随返回图标和首页图标一同出现，这时有一个差别就是，返回上一页的时候，图标和文字点击都会跳转（看代码是包在同一个view里面了），但是新修复的返回首页图标和backText同时在一起显示，此时的backText点击是没反应的，测试时候因为感官上的意识，一直再点击backText文字，没有反应，再去点击图标才有效果。

感谢建议！已经修改：
1、自定义跳转参数homePage，传入参数可自定义分享返回的页面；另外加了一个homeText参数，设置分享返回页面的文字，与backText使用方法一样。注意分享页面backText不再生效，正常页面homeText不生效。
2、点击图标和文字都会跳转。

**Comment by echome123** [comment]
完美，辛苦了，祝新年快乐

**Comment by XiaokangLei** [comment]
> 完美，辛苦了，祝新年快乐

新年快乐！
